name: Flutter CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Set up Java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Step 3: Set up Flutter
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.11'

      # Step 4: Get dependencies
      - run: flutter pub get

      # Step 5: Analyze code
      - run: flutter analyze

      # Step 6: Format code
      - run: flutter format -n --set-exit-if-changed .

      # Step 7: Run tests
      - run: flutter test

      # Step 8: Build APK
      - run: flutter build apk

      # Step 9: Upload artifact
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
